### ISSUE TITLE
Relevance of errors in García et al. (2010)

### ISSUE THREAD

**Issue by leezu** [b0rxa/scmamp#6]
In the Statistical_assessment_of_the_differences vignette you state

> In addition, the Friedman’s Aligned Rank Test and Quade Test presented in García et al. (2010) have been implemented—Note that this paper includes some errors in the computations due to some bugs in their code; for this reason, the results obtained with this package may not match those in the paper.

Do you know if these bugs affect any of the conclusions reached by García et al. (2010) about the recommendations regarding the use of Friedman’s Aligned Rank Test and Quade Test? Would it make sense to add a sentence clarifying the effect of these bugs to the vignette?

**Comment by gsantafe** [comment]
Dear leezu,

the bug in Garcia et al. (2010) is related to the formula of the post-hoc statistic in the Friedman aligned rank test. You can find more details in _Santafe, G., Inza, I. & Lozano, J.A. Artif Intell Rev (2015) 44: 467_ (in page 498). Thus, if you compare the results obtained with the scmamp software with those published in some articles you may find differences in the p-values of the pairwise comparisons when using the Friedman aligned rank test. The bug was notified to Garcia et al. and it should be already corrected in their software.

Due to this bug is in the post-hoc statistic it does not affect to general conclusions reached by Garcia et al. (2010) about the recommendations regarding the use of Friedman’s Aligned Rank Test and Quade Test. Additionally, general conclusions regarding post-hoc test are neither affected since they are about a general behavior of the post-hoc tests.

**Comment by leezu** [comment]
Thanks @gsantafe for the clarification and the reference to your paper. Thank you also for publishing this package.
